[project]
name = "lesswrong-llm-detection-experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "copyleaks>=4.3.0",
    "mypy>=1.15.0",
    "pandas-stubs>=2.2.3.250308",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "streamlit>=1.45.0",
    "tqdm>=4.67.1",
    "types-requests>=2.32.0.20250328",
    "types-tqdm>=4.67.0.20250417",
]
